// Autogenerated from Pigeon (v12.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "messages.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

@implementation FeeTypeBox
- (instancetype)initWithValue:(FeeType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation CurrencyTypeBox
- (instancetype)initWithValue:(CurrencyType)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

static NSArray *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}
static id GetNullableObjectAtIndex(NSArray *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface FeeMessage ()
+ (FeeMessage *)fromList:(NSArray *)list;
+ (nullable FeeMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface SendMessage ()
+ (SendMessage *)fromList:(NSArray *)list;
+ (nullable SendMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface ValidateAddressMessage ()
+ (ValidateAddressMessage *)fromList:(NSArray *)list;
+ (nullable ValidateAddressMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface FeeResponse ()
+ (FeeResponse *)fromList:(NSArray *)list;
+ (nullable FeeResponse *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface SendTransactionResponse ()
+ (SendTransactionResponse *)fromList:(NSArray *)list;
+ (nullable SendTransactionResponse *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface BlockchainErrorMessage ()
+ (BlockchainErrorMessage *)fromList:(NSArray *)list;
+ (nullable BlockchainErrorMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface BalanceResponse ()
+ (BalanceResponse *)fromList:(NSArray *)list;
+ (nullable BalanceResponse *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface CurrencyInfoMessage ()
+ (CurrencyInfoMessage *)fromList:(NSArray *)list;
+ (nullable CurrencyInfoMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface CardMessage ()
+ (CardMessage *)fromList:(NSArray *)list;
+ (nullable CardMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface TransactionHistoryRequest ()
+ (TransactionHistoryRequest *)fromList:(NSArray *)list;
+ (nullable TransactionHistoryRequest *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface TransactionsHistory ()
+ (TransactionsHistory *)fromList:(NSArray *)list;
+ (nullable TransactionsHistory *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface CommandResponse ()
+ (CommandResponse *)fromList:(NSArray *)list;
+ (nullable CommandResponse *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface SendCommandMessage ()
+ (SendCommandMessage *)fromList:(NSArray *)list;
+ (nullable SendCommandMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface ChainKeyMessage ()
+ (ChainKeyMessage *)fromList:(NSArray *)list;
+ (nullable ChainKeyMessage *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@interface ChainKeyInfo ()
+ (ChainKeyInfo *)fromList:(NSArray *)list;
+ (nullable ChainKeyInfo *)nullableFromList:(NSArray *)list;
- (NSArray *)toList;
@end

@implementation FeeMessage
+ (instancetype)makeWithSymbol:(NSString *)symbol
    blockchain:(NSString *)blockchain
    currencyType:(NSString *)currencyType
    receiverAddress:(NSString *)receiverAddress
    sumToSend:(NSString *)sumToSend
    isTest:(NSString *)isTest {
  FeeMessage* pigeonResult = [[FeeMessage alloc] init];
  pigeonResult.symbol = symbol;
  pigeonResult.blockchain = blockchain;
  pigeonResult.currencyType = currencyType;
  pigeonResult.receiverAddress = receiverAddress;
  pigeonResult.sumToSend = sumToSend;
  pigeonResult.isTest = isTest;
  return pigeonResult;
}
+ (FeeMessage *)fromList:(NSArray *)list {
  FeeMessage *pigeonResult = [[FeeMessage alloc] init];
  pigeonResult.symbol = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.symbol != nil, @"");
  pigeonResult.blockchain = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.blockchain != nil, @"");
  pigeonResult.currencyType = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.currencyType != nil, @"");
  pigeonResult.receiverAddress = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.receiverAddress != nil, @"");
  pigeonResult.sumToSend = GetNullableObjectAtIndex(list, 4);
  NSAssert(pigeonResult.sumToSend != nil, @"");
  pigeonResult.isTest = GetNullableObjectAtIndex(list, 5);
  NSAssert(pigeonResult.isTest != nil, @"");
  return pigeonResult;
}
+ (nullable FeeMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [FeeMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.symbol ?: [NSNull null]),
    (self.blockchain ?: [NSNull null]),
    (self.currencyType ?: [NSNull null]),
    (self.receiverAddress ?: [NSNull null]),
    (self.sumToSend ?: [NSNull null]),
    (self.isTest ?: [NSNull null]),
  ];
}
@end

@implementation SendMessage
+ (instancetype)makeWithSymbol:(nullable NSString *)symbol
    blockchainId:(NSString *)blockchainId
    currencyType:(NSString *)currencyType
    walletAddress:(NSString *)walletAddress
    fee:(NSString *)fee
    sumToSend:(NSString *)sumToSend
    receiverAddress:(NSString *)receiverAddress
    gasLimit:(nullable NSString *)gasLimit
    gasPrice:(nullable NSString *)gasPrice
    isTest:(NSString *)isTest {
  SendMessage* pigeonResult = [[SendMessage alloc] init];
  pigeonResult.symbol = symbol;
  pigeonResult.blockchainId = blockchainId;
  pigeonResult.currencyType = currencyType;
  pigeonResult.walletAddress = walletAddress;
  pigeonResult.fee = fee;
  pigeonResult.sumToSend = sumToSend;
  pigeonResult.receiverAddress = receiverAddress;
  pigeonResult.gasLimit = gasLimit;
  pigeonResult.gasPrice = gasPrice;
  pigeonResult.isTest = isTest;
  return pigeonResult;
}
+ (SendMessage *)fromList:(NSArray *)list {
  SendMessage *pigeonResult = [[SendMessage alloc] init];
  pigeonResult.symbol = GetNullableObjectAtIndex(list, 0);
  pigeonResult.blockchainId = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.blockchainId != nil, @"");
  pigeonResult.currencyType = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.currencyType != nil, @"");
  pigeonResult.walletAddress = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.walletAddress != nil, @"");
  pigeonResult.fee = GetNullableObjectAtIndex(list, 4);
  NSAssert(pigeonResult.fee != nil, @"");
  pigeonResult.sumToSend = GetNullableObjectAtIndex(list, 5);
  NSAssert(pigeonResult.sumToSend != nil, @"");
  pigeonResult.receiverAddress = GetNullableObjectAtIndex(list, 6);
  NSAssert(pigeonResult.receiverAddress != nil, @"");
  pigeonResult.gasLimit = GetNullableObjectAtIndex(list, 7);
  pigeonResult.gasPrice = GetNullableObjectAtIndex(list, 8);
  pigeonResult.isTest = GetNullableObjectAtIndex(list, 9);
  NSAssert(pigeonResult.isTest != nil, @"");
  return pigeonResult;
}
+ (nullable SendMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [SendMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.symbol ?: [NSNull null]),
    (self.blockchainId ?: [NSNull null]),
    (self.currencyType ?: [NSNull null]),
    (self.walletAddress ?: [NSNull null]),
    (self.fee ?: [NSNull null]),
    (self.sumToSend ?: [NSNull null]),
    (self.receiverAddress ?: [NSNull null]),
    (self.gasLimit ?: [NSNull null]),
    (self.gasPrice ?: [NSNull null]),
    (self.isTest ?: [NSNull null]),
  ];
}
@end

@implementation ValidateAddressMessage
+ (instancetype)makeWithBlockchain:(NSString *)blockchain
    address:(NSString *)address
    isTest:(NSString *)isTest {
  ValidateAddressMessage* pigeonResult = [[ValidateAddressMessage alloc] init];
  pigeonResult.blockchain = blockchain;
  pigeonResult.address = address;
  pigeonResult.isTest = isTest;
  return pigeonResult;
}
+ (ValidateAddressMessage *)fromList:(NSArray *)list {
  ValidateAddressMessage *pigeonResult = [[ValidateAddressMessage alloc] init];
  pigeonResult.blockchain = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.blockchain != nil, @"");
  pigeonResult.address = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.address != nil, @"");
  pigeonResult.isTest = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.isTest != nil, @"");
  return pigeonResult;
}
+ (nullable ValidateAddressMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [ValidateAddressMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.blockchain ?: [NSNull null]),
    (self.address ?: [NSNull null]),
    (self.isTest ?: [NSNull null]),
  ];
}
@end

@implementation FeeResponse
+ (instancetype)makeWithType:(FeeType)type
    value:(NSNumber *)value
    gasLimit:(nullable NSString *)gasLimit
    gasPrice:(nullable NSString *)gasPrice {
  FeeResponse* pigeonResult = [[FeeResponse alloc] init];
  pigeonResult.type = type;
  pigeonResult.value = value;
  pigeonResult.gasLimit = gasLimit;
  pigeonResult.gasPrice = gasPrice;
  return pigeonResult;
}
+ (FeeResponse *)fromList:(NSArray *)list {
  FeeResponse *pigeonResult = [[FeeResponse alloc] init];
  pigeonResult.type = [GetNullableObjectAtIndex(list, 0) integerValue];
  pigeonResult.value = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.value != nil, @"");
  pigeonResult.gasLimit = GetNullableObjectAtIndex(list, 2);
  pigeonResult.gasPrice = GetNullableObjectAtIndex(list, 3);
  return pigeonResult;
}
+ (nullable FeeResponse *)nullableFromList:(NSArray *)list {
  return (list) ? [FeeResponse fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    @(self.type),
    (self.value ?: [NSNull null]),
    (self.gasLimit ?: [NSNull null]),
    (self.gasPrice ?: [NSNull null]),
  ];
}
@end

@implementation SendTransactionResponse
+ (instancetype)makeWithIsSuccess:(NSNumber *)isSuccess
    errorMsg:(nullable NSString *)errorMsg {
  SendTransactionResponse* pigeonResult = [[SendTransactionResponse alloc] init];
  pigeonResult.isSuccess = isSuccess;
  pigeonResult.errorMsg = errorMsg;
  return pigeonResult;
}
+ (SendTransactionResponse *)fromList:(NSArray *)list {
  SendTransactionResponse *pigeonResult = [[SendTransactionResponse alloc] init];
  pigeonResult.isSuccess = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.isSuccess != nil, @"");
  pigeonResult.errorMsg = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable SendTransactionResponse *)nullableFromList:(NSArray *)list {
  return (list) ? [SendTransactionResponse fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.isSuccess ?: [NSNull null]),
    (self.errorMsg ?: [NSNull null]),
  ];
}
@end

@implementation BlockchainErrorMessage
+ (instancetype)makeWithCode:(NSNumber *)code
    customMessage:(NSString *)customMessage {
  BlockchainErrorMessage* pigeonResult = [[BlockchainErrorMessage alloc] init];
  pigeonResult.code = code;
  pigeonResult.customMessage = customMessage;
  return pigeonResult;
}
+ (BlockchainErrorMessage *)fromList:(NSArray *)list {
  BlockchainErrorMessage *pigeonResult = [[BlockchainErrorMessage alloc] init];
  pigeonResult.code = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.code != nil, @"");
  pigeonResult.customMessage = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.customMessage != nil, @"");
  return pigeonResult;
}
+ (nullable BlockchainErrorMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [BlockchainErrorMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.code ?: [NSNull null]),
    (self.customMessage ?: [NSNull null]),
  ];
}
@end

@implementation BalanceResponse
+ (instancetype)makeWithData:(CurrencyInfoMessage *)data
    errorMessage:(nullable BlockchainErrorMessage *)errorMessage {
  BalanceResponse* pigeonResult = [[BalanceResponse alloc] init];
  pigeonResult.data = data;
  pigeonResult.errorMessage = errorMessage;
  return pigeonResult;
}
+ (BalanceResponse *)fromList:(NSArray *)list {
  BalanceResponse *pigeonResult = [[BalanceResponse alloc] init];
  pigeonResult.data = [CurrencyInfoMessage nullableFromList:(GetNullableObjectAtIndex(list, 0))];
  NSAssert(pigeonResult.data != nil, @"");
  pigeonResult.errorMessage = [BlockchainErrorMessage nullableFromList:(GetNullableObjectAtIndex(list, 1))];
  return pigeonResult;
}
+ (nullable BalanceResponse *)nullableFromList:(NSArray *)list {
  return (list) ? [BalanceResponse fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.data ? [self.data toList] : [NSNull null]),
    (self.errorMessage ? [self.errorMessage toList] : [NSNull null]),
  ];
}
@end

@implementation CurrencyInfoMessage
+ (instancetype)makeWithId:(NSString *)id
    icon:(NSString *)icon
    name:(NSString *)name
    networkId:(NSString *)networkId
    networkName:(nullable NSString *)networkName
    networkIcon:(NSString *)networkIcon
    symbol:(NSString *)symbol
    contractAddress:(nullable NSString *)contractAddress
    decimalCount:(nullable NSNumber *)decimalCount
    amount:(nullable NSNumber *)amount
    address:(nullable NSString *)address
    publicKey:(nullable FlutterStandardTypedData *)publicKey
    chainCode:(nullable FlutterStandardTypedData *)chainCode
    isTest:(nullable NSNumber *)isTest {
  CurrencyInfoMessage* pigeonResult = [[CurrencyInfoMessage alloc] init];
  pigeonResult.id = id;
  pigeonResult.icon = icon;
  pigeonResult.name = name;
  pigeonResult.networkId = networkId;
  pigeonResult.networkName = networkName;
  pigeonResult.networkIcon = networkIcon;
  pigeonResult.symbol = symbol;
  pigeonResult.contractAddress = contractAddress;
  pigeonResult.decimalCount = decimalCount;
  pigeonResult.amount = amount;
  pigeonResult.address = address;
  pigeonResult.publicKey = publicKey;
  pigeonResult.chainCode = chainCode;
  pigeonResult.isTest = isTest;
  return pigeonResult;
}
+ (CurrencyInfoMessage *)fromList:(NSArray *)list {
  CurrencyInfoMessage *pigeonResult = [[CurrencyInfoMessage alloc] init];
  pigeonResult.id = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.id != nil, @"");
  pigeonResult.icon = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.icon != nil, @"");
  pigeonResult.name = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.name != nil, @"");
  pigeonResult.networkId = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.networkId != nil, @"");
  pigeonResult.networkName = GetNullableObjectAtIndex(list, 4);
  pigeonResult.networkIcon = GetNullableObjectAtIndex(list, 5);
  NSAssert(pigeonResult.networkIcon != nil, @"");
  pigeonResult.symbol = GetNullableObjectAtIndex(list, 6);
  NSAssert(pigeonResult.symbol != nil, @"");
  pigeonResult.contractAddress = GetNullableObjectAtIndex(list, 7);
  pigeonResult.decimalCount = GetNullableObjectAtIndex(list, 8);
  pigeonResult.amount = GetNullableObjectAtIndex(list, 9);
  pigeonResult.address = GetNullableObjectAtIndex(list, 10);
  pigeonResult.publicKey = GetNullableObjectAtIndex(list, 11);
  pigeonResult.chainCode = GetNullableObjectAtIndex(list, 12);
  pigeonResult.isTest = GetNullableObjectAtIndex(list, 13);
  return pigeonResult;
}
+ (nullable CurrencyInfoMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [CurrencyInfoMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.id ?: [NSNull null]),
    (self.icon ?: [NSNull null]),
    (self.name ?: [NSNull null]),
    (self.networkId ?: [NSNull null]),
    (self.networkName ?: [NSNull null]),
    (self.networkIcon ?: [NSNull null]),
    (self.symbol ?: [NSNull null]),
    (self.contractAddress ?: [NSNull null]),
    (self.decimalCount ?: [NSNull null]),
    (self.amount ?: [NSNull null]),
    (self.address ?: [NSNull null]),
    (self.publicKey ?: [NSNull null]),
    (self.chainCode ?: [NSNull null]),
    (self.isTest ?: [NSNull null]),
  ];
}
@end

@implementation CardMessage
+ (instancetype)makeWithUid:(NSString *)uid
    isPasswordSet:(NSNumber *)isPasswordSet
    publicKey:(nullable FlutterStandardTypedData *)publicKey
    currencyList:(NSArray<CurrencyInfoMessage *> *)currencyList {
  CardMessage* pigeonResult = [[CardMessage alloc] init];
  pigeonResult.uid = uid;
  pigeonResult.isPasswordSet = isPasswordSet;
  pigeonResult.publicKey = publicKey;
  pigeonResult.currencyList = currencyList;
  return pigeonResult;
}
+ (CardMessage *)fromList:(NSArray *)list {
  CardMessage *pigeonResult = [[CardMessage alloc] init];
  pigeonResult.uid = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.uid != nil, @"");
  pigeonResult.isPasswordSet = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.isPasswordSet != nil, @"");
  pigeonResult.publicKey = GetNullableObjectAtIndex(list, 2);
  pigeonResult.currencyList = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.currencyList != nil, @"");
  return pigeonResult;
}
+ (nullable CardMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [CardMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.uid ?: [NSNull null]),
    (self.isPasswordSet ?: [NSNull null]),
    (self.publicKey ?: [NSNull null]),
    (self.currencyList ?: [NSNull null]),
  ];
}
@end

@implementation TransactionHistoryRequest
+ (instancetype)makeWithAddress:(NSString *)address
    page:(nullable NSString *)page
    type:(NSNumber *)type
    currencyInfo:(CurrencyInfoMessage *)currencyInfo {
  TransactionHistoryRequest* pigeonResult = [[TransactionHistoryRequest alloc] init];
  pigeonResult.address = address;
  pigeonResult.page = page;
  pigeonResult.type = type;
  pigeonResult.currencyInfo = currencyInfo;
  return pigeonResult;
}
+ (TransactionHistoryRequest *)fromList:(NSArray *)list {
  TransactionHistoryRequest *pigeonResult = [[TransactionHistoryRequest alloc] init];
  pigeonResult.address = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.address != nil, @"");
  pigeonResult.page = GetNullableObjectAtIndex(list, 1);
  pigeonResult.type = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.type != nil, @"");
  pigeonResult.currencyInfo = [CurrencyInfoMessage nullableFromList:(GetNullableObjectAtIndex(list, 3))];
  NSAssert(pigeonResult.currencyInfo != nil, @"");
  return pigeonResult;
}
+ (nullable TransactionHistoryRequest *)nullableFromList:(NSArray *)list {
  return (list) ? [TransactionHistoryRequest fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.address ?: [NSNull null]),
    (self.page ?: [NSNull null]),
    (self.type ?: [NSNull null]),
    (self.currencyInfo ? [self.currencyInfo toList] : [NSNull null]),
  ];
}
@end

@implementation TransactionsHistory
+ (instancetype)makeWithTime:(NSNumber *)time
    direction:(NSNumber *)direction
    status:(NSNumber *)status
    type:(NSNumber *)type
    value:(NSNumber *)value
    decimals:(NSNumber *)decimals {
  TransactionsHistory* pigeonResult = [[TransactionsHistory alloc] init];
  pigeonResult.time = time;
  pigeonResult.direction = direction;
  pigeonResult.status = status;
  pigeonResult.type = type;
  pigeonResult.value = value;
  pigeonResult.decimals = decimals;
  return pigeonResult;
}
+ (TransactionsHistory *)fromList:(NSArray *)list {
  TransactionsHistory *pigeonResult = [[TransactionsHistory alloc] init];
  pigeonResult.time = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.time != nil, @"");
  pigeonResult.direction = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.direction != nil, @"");
  pigeonResult.status = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.status != nil, @"");
  pigeonResult.type = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.type != nil, @"");
  pigeonResult.value = GetNullableObjectAtIndex(list, 4);
  NSAssert(pigeonResult.value != nil, @"");
  pigeonResult.decimals = GetNullableObjectAtIndex(list, 5);
  NSAssert(pigeonResult.decimals != nil, @"");
  return pigeonResult;
}
+ (nullable TransactionsHistory *)nullableFromList:(NSArray *)list {
  return (list) ? [TransactionsHistory fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.time ?: [NSNull null]),
    (self.direction ?: [NSNull null]),
    (self.status ?: [NSNull null]),
    (self.type ?: [NSNull null]),
    (self.value ?: [NSNull null]),
    (self.decimals ?: [NSNull null]),
  ];
}
@end

@implementation CommandResponse
+ (instancetype)makeWithCardId:(NSString *)cardId
    appletVersionCode:(NSString *)appletVersionCode
    isActivated:(NSNumber *)isActivated
    resetCount:(NSNumber *)resetCount
    data:(nullable FlutterStandardTypedData *)data {
  CommandResponse* pigeonResult = [[CommandResponse alloc] init];
  pigeonResult.cardId = cardId;
  pigeonResult.appletVersionCode = appletVersionCode;
  pigeonResult.isActivated = isActivated;
  pigeonResult.resetCount = resetCount;
  pigeonResult.data = data;
  return pigeonResult;
}
+ (CommandResponse *)fromList:(NSArray *)list {
  CommandResponse *pigeonResult = [[CommandResponse alloc] init];
  pigeonResult.cardId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.cardId != nil, @"");
  pigeonResult.appletVersionCode = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.appletVersionCode != nil, @"");
  pigeonResult.isActivated = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.isActivated != nil, @"");
  pigeonResult.resetCount = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.resetCount != nil, @"");
  pigeonResult.data = GetNullableObjectAtIndex(list, 4);
  return pigeonResult;
}
+ (nullable CommandResponse *)nullableFromList:(NSArray *)list {
  return (list) ? [CommandResponse fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.cardId ?: [NSNull null]),
    (self.appletVersionCode ?: [NSNull null]),
    (self.isActivated ?: [NSNull null]),
    (self.resetCount ?: [NSNull null]),
    (self.data ?: [NSNull null]),
  ];
}
@end

@implementation SendCommandMessage
+ (instancetype)makeWithAppletId:(nullable FlutterStandardTypedData *)appletId
    cardId:(nullable NSString *)cardId
    command:(nullable FlutterStandardTypedData *)command
    checkLock:(nullable NSNumber *)checkLock
    ndefLink:(nullable NSString *)ndefLink
    cardNo:(nullable NSString *)cardNo
    checkPwd:(nullable NSNumber *)checkPwd {
  SendCommandMessage* pigeonResult = [[SendCommandMessage alloc] init];
  pigeonResult.appletId = appletId;
  pigeonResult.cardId = cardId;
  pigeonResult.command = command;
  pigeonResult.checkLock = checkLock;
  pigeonResult.ndefLink = ndefLink;
  pigeonResult.cardNo = cardNo;
  pigeonResult.checkPwd = checkPwd;
  return pigeonResult;
}
+ (SendCommandMessage *)fromList:(NSArray *)list {
  SendCommandMessage *pigeonResult = [[SendCommandMessage alloc] init];
  pigeonResult.appletId = GetNullableObjectAtIndex(list, 0);
  pigeonResult.cardId = GetNullableObjectAtIndex(list, 1);
  pigeonResult.command = GetNullableObjectAtIndex(list, 2);
  pigeonResult.checkLock = GetNullableObjectAtIndex(list, 3);
  pigeonResult.ndefLink = GetNullableObjectAtIndex(list, 4);
  pigeonResult.cardNo = GetNullableObjectAtIndex(list, 5);
  pigeonResult.checkPwd = GetNullableObjectAtIndex(list, 6);
  return pigeonResult;
}
+ (nullable SendCommandMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [SendCommandMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.appletId ?: [NSNull null]),
    (self.cardId ?: [NSNull null]),
    (self.command ?: [NSNull null]),
    (self.checkLock ?: [NSNull null]),
    (self.ndefLink ?: [NSNull null]),
    (self.cardNo ?: [NSNull null]),
    (self.checkPwd ?: [NSNull null]),
  ];
}
@end

@implementation ChainKeyMessage
+ (instancetype)makeWithBlockchainId:(NSString *)blockchainId
    chainId:(nullable NSNumber *)chainId
    privateKey:(NSString *)privateKey
    publicKey:(NSString *)publicKey
    address:(NSString *)address {
  ChainKeyMessage* pigeonResult = [[ChainKeyMessage alloc] init];
  pigeonResult.blockchainId = blockchainId;
  pigeonResult.chainId = chainId;
  pigeonResult.privateKey = privateKey;
  pigeonResult.publicKey = publicKey;
  pigeonResult.address = address;
  return pigeonResult;
}
+ (ChainKeyMessage *)fromList:(NSArray *)list {
  ChainKeyMessage *pigeonResult = [[ChainKeyMessage alloc] init];
  pigeonResult.blockchainId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.blockchainId != nil, @"");
  pigeonResult.chainId = GetNullableObjectAtIndex(list, 1);
  pigeonResult.privateKey = GetNullableObjectAtIndex(list, 2);
  NSAssert(pigeonResult.privateKey != nil, @"");
  pigeonResult.publicKey = GetNullableObjectAtIndex(list, 3);
  NSAssert(pigeonResult.publicKey != nil, @"");
  pigeonResult.address = GetNullableObjectAtIndex(list, 4);
  NSAssert(pigeonResult.address != nil, @"");
  return pigeonResult;
}
+ (nullable ChainKeyMessage *)nullableFromList:(NSArray *)list {
  return (list) ? [ChainKeyMessage fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.blockchainId ?: [NSNull null]),
    (self.chainId ?: [NSNull null]),
    (self.privateKey ?: [NSNull null]),
    (self.publicKey ?: [NSNull null]),
    (self.address ?: [NSNull null]),
  ];
}
@end

@implementation ChainKeyInfo
+ (instancetype)makeWithCardId:(NSString *)cardId
    chainKeys:(NSArray<ChainKeyMessage *> *)chainKeys {
  ChainKeyInfo* pigeonResult = [[ChainKeyInfo alloc] init];
  pigeonResult.cardId = cardId;
  pigeonResult.chainKeys = chainKeys;
  return pigeonResult;
}
+ (ChainKeyInfo *)fromList:(NSArray *)list {
  ChainKeyInfo *pigeonResult = [[ChainKeyInfo alloc] init];
  pigeonResult.cardId = GetNullableObjectAtIndex(list, 0);
  NSAssert(pigeonResult.cardId != nil, @"");
  pigeonResult.chainKeys = GetNullableObjectAtIndex(list, 1);
  NSAssert(pigeonResult.chainKeys != nil, @"");
  return pigeonResult;
}
+ (nullable ChainKeyInfo *)nullableFromList:(NSArray *)list {
  return (list) ? [ChainKeyInfo fromList:list] : nil;
}
- (NSArray *)toList {
  return @[
    (self.cardId ?: [NSNull null]),
    (self.chainKeys ?: [NSNull null]),
  ];
}
@end

@interface BlockchainApiCodecReader : FlutterStandardReader
@end
@implementation BlockchainApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [CardMessage fromList:[self readValue]];
    case 129: 
      return [ChainKeyInfo fromList:[self readValue]];
    case 130: 
      return [ChainKeyMessage fromList:[self readValue]];
    case 131: 
      return [CommandResponse fromList:[self readValue]];
    case 132: 
      return [CurrencyInfoMessage fromList:[self readValue]];
    case 133: 
      return [FeeMessage fromList:[self readValue]];
    case 134: 
      return [FeeResponse fromList:[self readValue]];
    case 135: 
      return [SendCommandMessage fromList:[self readValue]];
    case 136: 
      return [SendMessage fromList:[self readValue]];
    case 137: 
      return [SendTransactionResponse fromList:[self readValue]];
    case 138: 
      return [TransactionHistoryRequest fromList:[self readValue]];
    case 139: 
      return [TransactionsHistory fromList:[self readValue]];
    case 140: 
      return [ValidateAddressMessage fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface BlockchainApiCodecWriter : FlutterStandardWriter
@end
@implementation BlockchainApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[CardMessage class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ChainKeyInfo class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ChainKeyMessage class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CommandResponse class]]) {
    [self writeByte:131];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CurrencyInfoMessage class]]) {
    [self writeByte:132];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FeeMessage class]]) {
    [self writeByte:133];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[FeeResponse class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[SendCommandMessage class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[SendMessage class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[SendTransactionResponse class]]) {
    [self writeByte:137];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[TransactionHistoryRequest class]]) {
    [self writeByte:138];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[TransactionsHistory class]]) {
    [self writeByte:139];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[ValidateAddressMessage class]]) {
    [self writeByte:140];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface BlockchainApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation BlockchainApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[BlockchainApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[BlockchainApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *BlockchainApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    BlockchainApiCodecReaderWriter *readerWriter = [[BlockchainApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

void SetUpBlockchainApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BlockchainApi> *api) {
  /// 发送拍卡命令
  /// [command]请求命令数据
  /// [checkPwd]是否需要检查密码
  /// [checkLock]是否需要检查卡片已锁
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.scanCardWithCommand"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(scanCardWithCommandSendCommandMessage:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(scanCardWithCommandSendCommandMessage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        SendCommandMessage *arg_sendCommandMessage = GetNullableObjectAtIndex(args, 0);
        [api scanCardWithCommandSendCommandMessage:arg_sendCommandMessage completion:^(CommandResponse *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.scanCardAndDerive"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(scanCardAndDeriveCurrencyList:ndefLink:cardId:cardNo:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(scanCardAndDeriveCurrencyList:ndefLink:cardId:cardNo:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSArray<CurrencyInfoMessage *> *arg_currencyList = GetNullableObjectAtIndex(args, 0);
        NSString *arg_ndefLink = GetNullableObjectAtIndex(args, 1);
        NSString *arg_cardId = GetNullableObjectAtIndex(args, 2);
        NSString *arg_cardNo = GetNullableObjectAtIndex(args, 3);
        [api scanCardAndDeriveCurrencyList:arg_currencyList ndefLink:arg_ndefLink cardId:arg_cardId cardNo:arg_cardNo completion:^(CardMessage *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.createWalletAndDerive"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createWalletAndDeriveCurrencyList:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(createWalletAndDeriveCurrencyList:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSArray<CurrencyInfoMessage *> *arg_currencyList = GetNullableObjectAtIndex(args, 0);
        [api createWalletAndDeriveCurrencyList:arg_currencyList completion:^(CardMessage *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.loadCurrencyInfoList"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(loadCurrencyInfoListCurrencyList:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(loadCurrencyInfoListCurrencyList:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSArray<CurrencyInfoMessage *> *arg_currencyList = GetNullableObjectAtIndex(args, 0);
        [api loadCurrencyInfoListCurrencyList:arg_currencyList completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///初始化钱包
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.initScanResponse"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(initScanResponseUuid:error:)], @"BlockchainApi api (%@) doesn't respond to @selector(initScanResponseUuid:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_uuid = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api initScanResponseUuid:arg_uuid error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///添加币种
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.addCurrencyList"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(addCurrencyListCurrencyList:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(addCurrencyListCurrencyList:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSArray<CurrencyInfoMessage *> *arg_currencyList = GetNullableObjectAtIndex(args, 0);
        [api addCurrencyListCurrencyList:arg_currencyList completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///获取交易手续费
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.getFee"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getFeeFeeMessage:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(getFeeFeeMessage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        FeeMessage *arg_feeMessage = GetNullableObjectAtIndex(args, 0);
        [api getFeeFeeMessage:arg_feeMessage completion:^(NSArray<FeeResponse *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///发送交易合约
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.sendTransaction"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendTransactionSendMessage:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(sendTransactionSendMessage:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        SendMessage *arg_sendMessage = GetNullableObjectAtIndex(args, 0);
        [api sendTransactionSendMessage:arg_sendMessage completion:^(SendTransactionResponse *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///验证钱包地址
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.validateAddress"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(validateAddressValidateMessage:error:)], @"BlockchainApi api (%@) doesn't respond to @selector(validateAddressValidateMessage:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        ValidateAddressMessage *arg_validateMessage = GetNullableObjectAtIndex(args, 0);
        FlutterError *error;
        NSNumber *output = [api validateAddressValidateMessage:arg_validateMessage error:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///清除原生币种缓存数据
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.clearLocalCurrency"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(clearLocalCurrencyCardId:coinIds:error:)], @"BlockchainApi api (%@) doesn't respond to @selector(clearLocalCurrencyCardId:coinIds:error:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_cardId = GetNullableObjectAtIndex(args, 0);
        NSArray<NSString *> *arg_coinIds = GetNullableObjectAtIndex(args, 1);
        FlutterError *error;
        [api clearLocalCurrencyCardId:arg_cardId coinIds:arg_coinIds error:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.loadTransactionHistoryList"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(loadTransactionHistoryListRequest:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(loadTransactionHistoryListRequest:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        TransactionHistoryRequest *arg_request = GetNullableObjectAtIndex(args, 0);
        [api loadTransactionHistoryListRequest:arg_request completion:^(NSArray<TransactionsHistory *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///切换钱包
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.changeWallet"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(changeWalletCardId:currencyList:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(changeWalletCardId:currencyList:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_cardId = GetNullableObjectAtIndex(args, 0);
        NSArray<CurrencyInfoMessage *> *arg_currencyList = GetNullableObjectAtIndex(args, 1);
        [api changeWalletCardId:arg_cardId currencyList:arg_currencyList completion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  ///上传奔溃信息
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.postCatchedException"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(postCatchedExceptionError:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(postCatchedExceptionError:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_error = GetNullableObjectAtIndex(args, 0);
        [api postCatchedExceptionError:arg_error completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.signLightning"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(signLightningSignText:isBtc:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(signLightningSignText:isBtc:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_signText = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_isBtc = GetNullableObjectAtIndex(args, 1);
        [api signLightningSignText:arg_signText isBtc:arg_isBtc completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.createChainKeys"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(createChainKeysBlockchains:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(createChainKeysBlockchains:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSArray<NSString *> *arg_blockchains = GetNullableObjectAtIndex(args, 0);
        [api createChainKeysBlockchains:arg_blockchains completion:^(ChainKeyInfo *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.getChainKeys"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getChainKeysCardId:blockchains:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(getChainKeysCardId:blockchains:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_cardId = GetNullableObjectAtIndex(args, 0);
        NSArray<NSString *> *arg_blockchains = GetNullableObjectAtIndex(args, 1);
        [api getChainKeysCardId:arg_cardId blockchains:arg_blockchains completion:^(NSArray<ChainKeyMessage *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.signText"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(signTextBlockchainId:text:chainId:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(signTextBlockchainId:text:chainId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_blockchainId = GetNullableObjectAtIndex(args, 0);
        FlutterStandardTypedData *arg_text = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_chainId = GetNullableObjectAtIndex(args, 2);
        [api signTextBlockchainId:arg_blockchainId text:arg_text chainId:arg_chainId completion:^(FlutterStandardTypedData *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.signTransaction"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(signTransactionBlockchainId:text:chainId:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(signTransactionBlockchainId:text:chainId:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_blockchainId = GetNullableObjectAtIndex(args, 0);
        FlutterStandardTypedData *arg_text = GetNullableObjectAtIndex(args, 1);
        NSNumber *arg_chainId = GetNullableObjectAtIndex(args, 2);
        [api signTransactionBlockchainId:arg_blockchainId text:arg_text chainId:arg_chainId completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.getBitcoinPublicKey"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getBitcoinPublicKeyWithError:)], @"BlockchainApi api (%@) doesn't respond to @selector(getBitcoinPublicKeyWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api getBitcoinPublicKeyWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.resetNfcReaderMode"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(resetNfcReaderModeWithError:)], @"BlockchainApi api (%@) doesn't respond to @selector(resetNfcReaderModeWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api resetNfcReaderModeWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.getEthPublicKey"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(getEthPublicKeyWithError:)], @"BlockchainApi api (%@) doesn't respond to @selector(getEthPublicKeyWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api getEthPublicKeyWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.makeAddresses"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(makeAddressesNetworkId:isBtc:completion:)], @"BlockchainApi api (%@) doesn't respond to @selector(makeAddressesNetworkId:isBtc:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray *args = message;
        NSString *arg_networkId = GetNullableObjectAtIndex(args, 0);
        NSNumber *arg_isBtc = GetNullableObjectAtIndex(args, 1);
        [api makeAddressesNetworkId:arg_networkId isBtc:arg_isBtc completion:^(NSString *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.bindNetwork"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(bindNetworkWithError:)], @"BlockchainApi api (%@) doesn't respond to @selector(bindNetworkWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        [api bindNetworkWithError:&error];
        callback(wrapResult(nil, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.card_coin.BlockchainApi.isVpnActive"
        binaryMessenger:binaryMessenger
        codec:BlockchainApiGetCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isVpnActiveWithError:)], @"BlockchainApi api (%@) doesn't respond to @selector(isVpnActiveWithError:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api isVpnActiveWithError:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface FlutterClientApiCodecReader : FlutterStandardReader
@end
@implementation FlutterClientApiCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 128: 
      return [BalanceResponse fromList:[self readValue]];
    case 129: 
      return [BlockchainErrorMessage fromList:[self readValue]];
    case 130: 
      return [CurrencyInfoMessage fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface FlutterClientApiCodecWriter : FlutterStandardWriter
@end
@implementation FlutterClientApiCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[BalanceResponse class]]) {
    [self writeByte:128];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[BlockchainErrorMessage class]]) {
    [self writeByte:129];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[CurrencyInfoMessage class]]) {
    [self writeByte:130];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface FlutterClientApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FlutterClientApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[FlutterClientApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[FlutterClientApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *FlutterClientApiGetCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    FlutterClientApiCodecReaderWriter *readerWriter = [[FlutterClientApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}

@interface FlutterClientApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@end

@implementation FlutterClientApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  self = [super init];
  if (self) {
    _binaryMessenger = binaryMessenger;
  }
  return self;
}
- (void)updateCurrencyInfoCurrencyInfoList:(NSArray<BalanceResponse *> *)arg_currencyInfoList completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion {
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:@"dev.flutter.pigeon.card_coin.FlutterClientApi.updateCurrencyInfo"
      binaryMessenger:self.binaryMessenger
      codec:FlutterClientApiGetCodec()];
  [channel sendMessage:@[arg_currencyInfoList ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSNumber *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, [FlutterError errorWithCode:@"channel-error" message:@"Unable to establish connection on channel." details:@""]);
    } 
  }];
}
@end

