// Autogenerated from Pigeon (v12.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

enum FeeType: Int {
  case low = 0
  case normal = 1
  case priority = 2
}

enum CurrencyType: Int {
  case coin = 0
  case token = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct FeeMessage {
  var symbol: String
  var blockchain: String
  var currencyType: String
  var receiverAddress: String
  var sumToSend: String
  var isTest: String

  static func fromList(_ list: [Any?]) -> FeeMessage? {
    let symbol = list[0] as! String
    let blockchain = list[1] as! String
    let currencyType = list[2] as! String
    let receiverAddress = list[3] as! String
    let sumToSend = list[4] as! String
    let isTest = list[5] as! String

    return FeeMessage(
      symbol: symbol,
      blockchain: blockchain,
      currencyType: currencyType,
      receiverAddress: receiverAddress,
      sumToSend: sumToSend,
      isTest: isTest
    )
  }
  func toList() -> [Any?] {
    return [
      symbol,
      blockchain,
      currencyType,
      receiverAddress,
      sumToSend,
      isTest,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SendMessage {
  var symbol: String? = nil
  var blockchainId: String
  var currencyType: String
  var walletAddress: String
  var fee: String
  var sumToSend: String
  var receiverAddress: String
  var gasLimit: String? = nil
  var gasPrice: String? = nil
  var isTest: String

  static func fromList(_ list: [Any?]) -> SendMessage? {
    let symbol: String? = nilOrValue(list[0])
    let blockchainId = list[1] as! String
    let currencyType = list[2] as! String
    let walletAddress = list[3] as! String
    let fee = list[4] as! String
    let sumToSend = list[5] as! String
    let receiverAddress = list[6] as! String
    let gasLimit: String? = nilOrValue(list[7])
    let gasPrice: String? = nilOrValue(list[8])
    let isTest = list[9] as! String

    return SendMessage(
      symbol: symbol,
      blockchainId: blockchainId,
      currencyType: currencyType,
      walletAddress: walletAddress,
      fee: fee,
      sumToSend: sumToSend,
      receiverAddress: receiverAddress,
      gasLimit: gasLimit,
      gasPrice: gasPrice,
      isTest: isTest
    )
  }
  func toList() -> [Any?] {
    return [
      symbol,
      blockchainId,
      currencyType,
      walletAddress,
      fee,
      sumToSend,
      receiverAddress,
      gasLimit,
      gasPrice,
      isTest,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ValidateAddressMessage {
  var blockchain: String
  var address: String
  var isTest: String

  static func fromList(_ list: [Any?]) -> ValidateAddressMessage? {
    let blockchain = list[0] as! String
    let address = list[1] as! String
    let isTest = list[2] as! String

    return ValidateAddressMessage(
      blockchain: blockchain,
      address: address,
      isTest: isTest
    )
  }
  func toList() -> [Any?] {
    return [
      blockchain,
      address,
      isTest,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FeeResponse {
  var type: FeeType
  var value: String
  var gasLimit: String? = nil
  var gasPrice: String? = nil

  static func fromList(_ list: [Any?]) -> FeeResponse? {
    let type = FeeType(rawValue: list[0] as! Int)!
    let value = list[1] as! String
    let gasLimit: String? = nilOrValue(list[2])
    let gasPrice: String? = nilOrValue(list[3])

    return FeeResponse(
      type: type,
      value: value,
      gasLimit: gasLimit,
      gasPrice: gasPrice
    )
  }
  func toList() -> [Any?] {
    return [
      type.rawValue,
      value,
      gasLimit,
      gasPrice,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SendTransactionResponse {
  var isSuccess: Bool
  var errorMsg: String? = nil

  static func fromList(_ list: [Any?]) -> SendTransactionResponse? {
    let isSuccess = list[0] as! Bool
    let errorMsg: String? = nilOrValue(list[1])

    return SendTransactionResponse(
      isSuccess: isSuccess,
      errorMsg: errorMsg
    )
  }
  func toList() -> [Any?] {
    return [
      isSuccess,
      errorMsg,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BlockchainErrorMessage {
  var code: Int64
  var customMessage: String

  static func fromList(_ list: [Any?]) -> BlockchainErrorMessage? {
    let code = list[0] is Int64 ? list[0] as! Int64 : Int64(list[0] as! Int32)
    let customMessage = list[1] as! String

    return BlockchainErrorMessage(
      code: code,
      customMessage: customMessage
    )
  }
  func toList() -> [Any?] {
    return [
      code,
      customMessage,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct BalanceResponse {
  var data: CurrencyInfoMessage
  var errorMessage: BlockchainErrorMessage? = nil

  static func fromList(_ list: [Any?]) -> BalanceResponse? {
    let data = CurrencyInfoMessage.fromList(list[0] as! [Any?])!
    var errorMessage: BlockchainErrorMessage? = nil
    if let errorMessageList: [Any?] = nilOrValue(list[1]) {
      errorMessage = BlockchainErrorMessage.fromList(errorMessageList)
    }

    return BalanceResponse(
      data: data,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      data.toList(),
      errorMessage?.toList(),
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CurrencyInfoMessage {
  var id: String
  var icon: String
  var name: String
  var networkId: String
  var networkName: String? = nil
  var networkIcon: String
  var symbol: String
  var contractAddress: String? = nil
  var decimalCount: Int64? = nil
  var amount: String? = nil
  var address: String? = nil
  var publicKey: FlutterStandardTypedData? = nil
  var chainCode: FlutterStandardTypedData? = nil
  var isTest: Int64? = nil

  static func fromList(_ list: [Any?]) -> CurrencyInfoMessage? {
    let id = list[0] as! String
    let icon = list[1] as! String
    let name = list[2] as! String
    let networkId = list[3] as! String
    let networkName: String? = nilOrValue(list[4])
    let networkIcon = list[5] as! String
    let symbol = list[6] as! String
    let contractAddress: String? = nilOrValue(list[7])
    let decimalCount: Int64? = isNullish(list[8]) ? nil : (list[8] is Int64? ? list[8] as! Int64? : Int64(list[8] as! Int32))
    let amount: String? = nilOrValue(list[9])
    let address: String? = nilOrValue(list[10])
    let publicKey: FlutterStandardTypedData? = nilOrValue(list[11])
    let chainCode: FlutterStandardTypedData? = nilOrValue(list[12])
    let isTest: Int64? = isNullish(list[13]) ? nil : (list[13] is Int64? ? list[13] as! Int64? : Int64(list[13] as! Int32))

    return CurrencyInfoMessage(
      id: id,
      icon: icon,
      name: name,
      networkId: networkId,
      networkName: networkName,
      networkIcon: networkIcon,
      symbol: symbol,
      contractAddress: contractAddress,
      decimalCount: decimalCount,
      amount: amount,
      address: address,
      publicKey: publicKey,
      chainCode: chainCode,
      isTest: isTest
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      icon,
      name,
      networkId,
      networkName,
      networkIcon,
      symbol,
      contractAddress,
      decimalCount,
      amount,
      address,
      publicKey,
      chainCode,
      isTest,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct CardMessage {
  var uid: String
  var isPasswordSet: Bool
  var publicKey: FlutterStandardTypedData? = nil
  var currencyList: [CurrencyInfoMessage?]

  static func fromList(_ list: [Any?]) -> CardMessage? {
    let uid = list[0] as! String
    let isPasswordSet = list[1] as! Bool
    let publicKey: FlutterStandardTypedData? = nilOrValue(list[2])
    let currencyList = list[3] as! [CurrencyInfoMessage?]

    return CardMessage(
      uid: uid,
      isPasswordSet: isPasswordSet,
      publicKey: publicKey,
      currencyList: currencyList
    )
  }
  func toList() -> [Any?] {
    return [
      uid,
      isPasswordSet,
      publicKey,
      currencyList,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TransactionHistoryRequest {
  var address: String
  var page: String? = nil
  var type: Int64
  var currencyInfo: CurrencyInfoMessage

  static func fromList(_ list: [Any?]) -> TransactionHistoryRequest? {
    let address = list[0] as! String
    let page: String? = nilOrValue(list[1])
    let type = list[2] is Int64 ? list[2] as! Int64 : Int64(list[2] as! Int32)
    let currencyInfo = CurrencyInfoMessage.fromList(list[3] as! [Any?])!

    return TransactionHistoryRequest(
      address: address,
      page: page,
      type: type,
      currencyInfo: currencyInfo
    )
  }
  func toList() -> [Any?] {
    return [
      address,
      page,
      type,
      currencyInfo.toList(),
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct TransactionsHistory {
  var time: Int64
  var direction: Int64
  var status: Int64
  var type: Int64
  var value: Double
  var decimals: Int64

  static func fromList(_ list: [Any?]) -> TransactionsHistory? {
    let time = list[0] is Int64 ? list[0] as! Int64 : Int64(list[0] as! Int32)
    let direction = list[1] is Int64 ? list[1] as! Int64 : Int64(list[1] as! Int32)
    let status = list[2] is Int64 ? list[2] as! Int64 : Int64(list[2] as! Int32)
    let type = list[3] is Int64 ? list[3] as! Int64 : Int64(list[3] as! Int32)
    let value = list[4] as! Double
    let decimals = list[5] is Int64 ? list[5] as! Int64 : Int64(list[5] as! Int32)

    return TransactionsHistory(
      time: time,
      direction: direction,
      status: status,
      type: type,
      value: value,
      decimals: decimals
    )
  }
  func toList() -> [Any?] {
    return [
      time,
      direction,
      status,
      type,
      value,
      decimals,
    ]
  }
}

/// [cardId]卡片ID
/// [data]命令结果
///
/// Generated class from Pigeon that represents data sent in messages.
struct CommandResponse {
  var cardId: String
  var appletVersionCode: String
  var appletVersion: String
  var isActivated: Bool
  var resetCount: Int64
  var data: FlutterStandardTypedData? = nil

  static func fromList(_ list: [Any?]) -> CommandResponse? {
    let cardId = list[0] as! String
    let appletVersionCode = list[1] as! String
    let appletVersion = list[2] as! String
    let isActivated = list[3] as! Bool
    let resetCount = list[4] is Int64 ? list[4] as! Int64 : Int64(list[4] as! Int32)
    let data: FlutterStandardTypedData? = nilOrValue(list[5])

    return CommandResponse(
      cardId: cardId,
      appletVersionCode: appletVersionCode,
      appletVersion: appletVersion,
      isActivated: isActivated,
      resetCount: resetCount,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      cardId,
      appletVersionCode,
      appletVersion,
      isActivated,
      resetCount,
      data,
    ]
  }
}

/// [command]请求命令数据
/// [checkPwd]是否需要检查密码
/// [checkLock]是否需要检查卡片已锁
/// [ndefLink]是否需要设置ndefLink
/// ///[ndefLink]是否需要设置ndefLink
///
/// Generated class from Pigeon that represents data sent in messages.
struct SendCommandMessage {
  var appletId: FlutterStandardTypedData? = nil
  var cardId: String? = nil
  var command: FlutterStandardTypedData? = nil
  var checkLock: Bool? = nil
  var ndefLink: String? = nil
  var ndefAar: String? = nil
  var cardNo: String? = nil
  var checkPwd: Bool? = nil
  var needRun: Bool? = nil
  var needSyscUid: Bool? = nil

  static func fromList(_ list: [Any?]) -> SendCommandMessage? {
    let appletId: FlutterStandardTypedData? = nilOrValue(list[0])
    let cardId: String? = nilOrValue(list[1])
    let command: FlutterStandardTypedData? = nilOrValue(list[2])
    let checkLock: Bool? = nilOrValue(list[3])
    let ndefLink: String? = nilOrValue(list[4])
    let ndefAar: String? = nilOrValue(list[5])
    let cardNo: String? = nilOrValue(list[6])
    let checkPwd: Bool? = nilOrValue(list[7])
    let needRun: Bool? = nilOrValue(list[8])
    let needSyscUid: Bool? = nilOrValue(list[9])

    return SendCommandMessage(
      appletId: appletId,
      cardId: cardId,
      command: command,
      checkLock: checkLock,
      ndefLink: ndefLink,
      ndefAar: ndefAar,
      cardNo: cardNo,
      checkPwd: checkPwd,
      needRun: needRun,
      needSyscUid: needSyscUid
    )
  }
  func toList() -> [Any?] {
    return [
      appletId,
      cardId,
      command,
      checkLock,
      ndefLink,
      ndefAar,
      cardNo,
      checkPwd,
      needRun,
      needSyscUid,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ChainKeyMessage {
  var blockchainId: String
  var chainId: Int64? = nil
  var privateKey: String
  var publicKey: String
  var address: String

  static func fromList(_ list: [Any?]) -> ChainKeyMessage? {
    let blockchainId = list[0] as! String
    let chainId: Int64? = isNullish(list[1]) ? nil : (list[1] is Int64? ? list[1] as! Int64? : Int64(list[1] as! Int32))
    let privateKey = list[2] as! String
    let publicKey = list[3] as! String
    let address = list[4] as! String

    return ChainKeyMessage(
      blockchainId: blockchainId,
      chainId: chainId,
      privateKey: privateKey,
      publicKey: publicKey,
      address: address
    )
  }
  func toList() -> [Any?] {
    return [
      blockchainId,
      chainId,
      privateKey,
      publicKey,
      address,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ChainKeyInfo {
  var cardId: String
  var chainKeys: [ChainKeyMessage?]

  static func fromList(_ list: [Any?]) -> ChainKeyInfo? {
    let cardId = list[0] as! String
    let chainKeys = list[1] as! [ChainKeyMessage?]

    return ChainKeyInfo(
      cardId: cardId,
      chainKeys: chainKeys
    )
  }
  func toList() -> [Any?] {
    return [
      cardId,
      chainKeys,
    ]
  }
}

private class BlockchainApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return CardMessage.fromList(self.readValue() as! [Any?])
      case 129:
        return ChainKeyInfo.fromList(self.readValue() as! [Any?])
      case 130:
        return ChainKeyMessage.fromList(self.readValue() as! [Any?])
      case 131:
        return CommandResponse.fromList(self.readValue() as! [Any?])
      case 132:
        return CurrencyInfoMessage.fromList(self.readValue() as! [Any?])
      case 133:
        return FeeMessage.fromList(self.readValue() as! [Any?])
      case 134:
        return FeeResponse.fromList(self.readValue() as! [Any?])
      case 135:
        return SendCommandMessage.fromList(self.readValue() as! [Any?])
      case 136:
        return SendMessage.fromList(self.readValue() as! [Any?])
      case 137:
        return SendTransactionResponse.fromList(self.readValue() as! [Any?])
      case 138:
        return TransactionHistoryRequest.fromList(self.readValue() as! [Any?])
      case 139:
        return TransactionsHistory.fromList(self.readValue() as! [Any?])
      case 140:
        return ValidateAddressMessage.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class BlockchainApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? CardMessage {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? ChainKeyInfo {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ChainKeyMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? CommandResponse {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? CurrencyInfoMessage {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? FeeMessage {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? FeeResponse {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? SendCommandMessage {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? SendMessage {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? SendTransactionResponse {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? TransactionHistoryRequest {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? TransactionsHistory {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? ValidateAddressMessage {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class BlockchainApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return BlockchainApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return BlockchainApiCodecWriter(data: data)
  }
}

class BlockchainApiCodec: FlutterStandardMessageCodec {
  static let shared = BlockchainApiCodec(readerWriter: BlockchainApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BlockchainApi {
  /// 发送拍卡命令
  /// [command]请求命令数据
  /// [checkPwd]是否需要检查密码
  /// [checkLock]是否需要检查卡片已锁
  func scanCardWithCommand(sendCommandMessage: SendCommandMessage, completion: @escaping (Result<CommandResponse, Error>) -> Void)
  func scanCardAndDerive(currencyList: [CurrencyInfoMessage], ndefLink: String, cardId: String?, cardNo: String?, completion: @escaping (Result<CardMessage, Error>) -> Void)
  func createWalletAndDerive(currencyList: [CurrencyInfoMessage], completion: @escaping (Result<CardMessage, Error>) -> Void)
  func loadCurrencyInfoList(currencyList: [CurrencyInfoMessage], completion: @escaping (Result<Void, Error>) -> Void)
  ///初始化钱包
  func initScanResponse(uuid: String) throws -> Bool
  ///添加币种
  func addCurrencyList(currencyList: [CurrencyInfoMessage], completion: @escaping (Result<Bool, Error>) -> Void)
  ///获取交易手续费
  func getFee(feeMessage: FeeMessage, completion: @escaping (Result<[FeeResponse], Error>) -> Void)
  ///发送交易合约
  func sendTransaction(sendMessage: SendMessage, completion: @escaping (Result<SendTransactionResponse, Error>) -> Void)
  ///验证钱包地址
  func validateAddress(validateMessage: ValidateAddressMessage) throws -> Bool
  ///清除原生币种缓存数据
  func clearLocalCurrency(cardId: String, coinIds: [String]) throws
  func loadTransactionHistoryList(request: TransactionHistoryRequest, completion: @escaping (Result<[TransactionsHistory], Error>) -> Void)
  ///切换钱包
  func changeWallet(cardId: String, currencyList: [CurrencyInfoMessage], completion: @escaping (Result<Bool, Error>) -> Void)
  ///上传奔溃信息
  func postCatchedException(error: String, completion: @escaping (Result<Void, Error>) -> Void)
  func signLightning(signText: String, isBtc: Bool, completion: @escaping (Result<String, Error>) -> Void)
  func createChainKeys(blockchains: [String], completion: @escaping (Result<ChainKeyInfo, Error>) -> Void)
  func getChainKeys(cardId: String, blockchains: [String], completion: @escaping (Result<[ChainKeyMessage], Error>) -> Void)
  func signText(blockchainId: String, text: String, chainId: Int64?, completion: @escaping (Result<String, Error>) -> Void)
  func signTransaction(blockchainId: String, text: String, chainId: Int64?, completion: @escaping (Result<String, Error>) -> Void)
  func generateKey(completion: @escaping (Result<String, Error>) -> Void)
  func signChallenge(challenge: String, completion: @escaping (Result<String, Error>) -> Void)
  func getBitcoinPublicKey() throws -> String
  func resetNfcReaderMode() throws
  func getEthPublicKey() throws -> String
  func makeAddresses(networkId: String, isBtc: Bool, completion: @escaping (Result<String, Error>) -> Void)
  func bindNetwork() throws
  func isVpnActive() throws -> Bool
  func isDualSim() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BlockchainApiSetup {
  /// The codec used by BlockchainApi.
  static var codec: FlutterStandardMessageCodec { BlockchainApiCodec.shared }
  /// Sets up an instance of `BlockchainApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BlockchainApi?) {
    /// 发送拍卡命令
    /// [command]请求命令数据
    /// [checkPwd]是否需要检查密码
    /// [checkLock]是否需要检查卡片已锁
    let scanCardWithCommandChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.scanCardWithCommand", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanCardWithCommandChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sendCommandMessageArg = args[0] as! SendCommandMessage
        api.scanCardWithCommand(sendCommandMessage: sendCommandMessageArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      scanCardWithCommandChannel.setMessageHandler(nil)
    }
    let scanCardAndDeriveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.scanCardAndDerive", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      scanCardAndDeriveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let currencyListArg = args[0] as! [CurrencyInfoMessage]
        let ndefLinkArg = args[1] as! String
        let cardIdArg: String? = nilOrValue(args[2])
        let cardNoArg: String? = nilOrValue(args[3])
        api.scanCardAndDerive(currencyList: currencyListArg, ndefLink: ndefLinkArg, cardId: cardIdArg, cardNo: cardNoArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      scanCardAndDeriveChannel.setMessageHandler(nil)
    }
    let createWalletAndDeriveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.createWalletAndDerive", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createWalletAndDeriveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let currencyListArg = args[0] as! [CurrencyInfoMessage]
        api.createWalletAndDerive(currencyList: currencyListArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      createWalletAndDeriveChannel.setMessageHandler(nil)
    }
    let loadCurrencyInfoListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.loadCurrencyInfoList", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadCurrencyInfoListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let currencyListArg = args[0] as! [CurrencyInfoMessage]
        api.loadCurrencyInfoList(currencyList: currencyListArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      loadCurrencyInfoListChannel.setMessageHandler(nil)
    }
    ///初始化钱包
    let initScanResponseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.initScanResponse", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initScanResponseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uuidArg = args[0] as! String
        do {
          let result = try api.initScanResponse(uuid: uuidArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initScanResponseChannel.setMessageHandler(nil)
    }
    ///添加币种
    let addCurrencyListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.addCurrencyList", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      addCurrencyListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let currencyListArg = args[0] as! [CurrencyInfoMessage]
        api.addCurrencyList(currencyList: currencyListArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      addCurrencyListChannel.setMessageHandler(nil)
    }
    ///获取交易手续费
    let getFeeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.getFee", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFeeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let feeMessageArg = args[0] as! FeeMessage
        api.getFee(feeMessage: feeMessageArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getFeeChannel.setMessageHandler(nil)
    }
    ///发送交易合约
    let sendTransactionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.sendTransaction", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendTransactionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sendMessageArg = args[0] as! SendMessage
        api.sendTransaction(sendMessage: sendMessageArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      sendTransactionChannel.setMessageHandler(nil)
    }
    ///验证钱包地址
    let validateAddressChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.validateAddress", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      validateAddressChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let validateMessageArg = args[0] as! ValidateAddressMessage
        do {
          let result = try api.validateAddress(validateMessage: validateMessageArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      validateAddressChannel.setMessageHandler(nil)
    }
    ///清除原生币种缓存数据
    let clearLocalCurrencyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.clearLocalCurrency", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      clearLocalCurrencyChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cardIdArg = args[0] as! String
        let coinIdsArg = args[1] as! [String]
        do {
          try api.clearLocalCurrency(cardId: cardIdArg, coinIds: coinIdsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      clearLocalCurrencyChannel.setMessageHandler(nil)
    }
    let loadTransactionHistoryListChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.loadTransactionHistoryList", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      loadTransactionHistoryListChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! TransactionHistoryRequest
        api.loadTransactionHistoryList(request: requestArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      loadTransactionHistoryListChannel.setMessageHandler(nil)
    }
    ///切换钱包
    let changeWalletChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.changeWallet", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      changeWalletChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cardIdArg = args[0] as! String
        let currencyListArg = args[1] as! [CurrencyInfoMessage]
        api.changeWallet(cardId: cardIdArg, currencyList: currencyListArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      changeWalletChannel.setMessageHandler(nil)
    }
    ///上传奔溃信息
    let postCatchedExceptionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.postCatchedException", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      postCatchedExceptionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let errorArg = args[0] as! String
        api.postCatchedException(error: errorArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      postCatchedExceptionChannel.setMessageHandler(nil)
    }
    let signLightningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.signLightning", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signLightningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let signTextArg = args[0] as! String
        let isBtcArg = args[1] as! Bool
        api.signLightning(signText: signTextArg, isBtc: isBtcArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      signLightningChannel.setMessageHandler(nil)
    }
    let createChainKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.createChainKeys", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createChainKeysChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let blockchainsArg = args[0] as! [String]
        api.createChainKeys(blockchains: blockchainsArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      createChainKeysChannel.setMessageHandler(nil)
    }
    let getChainKeysChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.getChainKeys", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getChainKeysChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let cardIdArg = args[0] as! String
        let blockchainsArg = args[1] as! [String]
        api.getChainKeys(cardId: cardIdArg, blockchains: blockchainsArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getChainKeysChannel.setMessageHandler(nil)
    }
    let signTextChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.signText", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signTextChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let blockchainIdArg = args[0] as! String
        let textArg = args[1] as! String
        let chainIdArg: Int64? = isNullish(args[2]) ? nil : (args[2] is Int64? ? args[2] as! Int64? : Int64(args[2] as! Int32))
        api.signText(blockchainId: blockchainIdArg, text: textArg, chainId: chainIdArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      signTextChannel.setMessageHandler(nil)
    }
    let signTransactionChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.signTransaction", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signTransactionChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let blockchainIdArg = args[0] as! String
        let textArg = args[1] as! String
        let chainIdArg: Int64? = isNullish(args[2]) ? nil : (args[2] is Int64? ? args[2] as! Int64? : Int64(args[2] as! Int32))
        api.signTransaction(blockchainId: blockchainIdArg, text: textArg, chainId: chainIdArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      signTransactionChannel.setMessageHandler(nil)
    }
    let generateKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.generateKey", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      generateKeyChannel.setMessageHandler { _, reply in
        api.generateKey() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      generateKeyChannel.setMessageHandler(nil)
    }
    let signChallengeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.signChallenge", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      signChallengeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let challengeArg = args[0] as! String
        api.signChallenge(challenge: challengeArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      signChallengeChannel.setMessageHandler(nil)
    }
    let getBitcoinPublicKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.getBitcoinPublicKey", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getBitcoinPublicKeyChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getBitcoinPublicKey()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getBitcoinPublicKeyChannel.setMessageHandler(nil)
    }
    let resetNfcReaderModeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.resetNfcReaderMode", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      resetNfcReaderModeChannel.setMessageHandler { _, reply in
        do {
          try api.resetNfcReaderMode()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      resetNfcReaderModeChannel.setMessageHandler(nil)
    }
    let getEthPublicKeyChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.getEthPublicKey", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getEthPublicKeyChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getEthPublicKey()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getEthPublicKeyChannel.setMessageHandler(nil)
    }
    let makeAddressesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.makeAddresses", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      makeAddressesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let networkIdArg = args[0] as! String
        let isBtcArg = args[1] as! Bool
        api.makeAddresses(networkId: networkIdArg, isBtc: isBtcArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      makeAddressesChannel.setMessageHandler(nil)
    }
    let bindNetworkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.bindNetwork", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      bindNetworkChannel.setMessageHandler { _, reply in
        do {
          try api.bindNetwork()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      bindNetworkChannel.setMessageHandler(nil)
    }
    let isVpnActiveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.isVpnActive", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isVpnActiveChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isVpnActive()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isVpnActiveChannel.setMessageHandler(nil)
    }
    let isDualSimChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.BlockchainApi.isDualSim", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isDualSimChannel.setMessageHandler { _, reply in
        do {
          let result = try api.isDualSim()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      isDualSimChannel.setMessageHandler(nil)
    }
  }
}
private class FlutterClientApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return BalanceResponse.fromList(self.readValue() as! [Any?])
      case 129:
        return BlockchainErrorMessage.fromList(self.readValue() as! [Any?])
      case 130:
        return CurrencyInfoMessage.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class FlutterClientApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BalanceResponse {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? BlockchainErrorMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? CurrencyInfoMessage {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class FlutterClientApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return FlutterClientApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return FlutterClientApiCodecWriter(data: data)
  }
}

class FlutterClientApiCodec: FlutterStandardMessageCodec {
  static let shared = FlutterClientApiCodec(readerWriter: FlutterClientApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol FlutterClientApiProtocol {
  ///更新数字币余额信息
  func updateCurrencyInfo(currencyInfoList currencyInfoListArg: [BalanceResponse], completion: @escaping (Result<Bool, FlutterError>) -> Void) 
}
class FlutterClientApi: FlutterClientApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return FlutterClientApiCodec.shared
  }
  ///更新数字币余额信息
  func updateCurrencyInfo(currencyInfoList currencyInfoListArg: [BalanceResponse], completion: @escaping (Result<Bool, FlutterError>) -> Void)  {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.card_coin.FlutterClientApi.updateCurrencyInfo", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([currencyInfoListArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(FlutterError(code: "channel-error", message: "Unable to establish connection on channel.", details: "")))
        return
      }
      if (listResponse.count > 1) {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(FlutterError(code: code, message: message, details: details)));
      } else if (listResponse[0] == nil) {
        completion(.failure(FlutterError(code: "null-error", message: "Flutter api returned null value for non-null return value.", details: "")))
      } else {
        let result = listResponse[0] as! Bool
        completion(.success(result))
      }
    }
  }
}
