// Autogenerated from Pigeon (v12.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, FeeType) {
  FeeTypeLow = 0,
  FeeTypeNormal = 1,
  FeeTypePriority = 2,
};

/// Wrapper for FeeType to allow for nullability.
@interface FeeTypeBox : NSObject
@property(nonatomic, assign) FeeType value;
- (instancetype)initWithValue:(FeeType)value;
@end

typedef NS_ENUM(NSUInteger, CurrencyType) {
  CurrencyTypeCoin = 0,
  CurrencyTypeToken = 1,
};

/// Wrapper for CurrencyType to allow for nullability.
@interface CurrencyTypeBox : NSObject
@property(nonatomic, assign) CurrencyType value;
- (instancetype)initWithValue:(CurrencyType)value;
@end

@class FeeMessage;
@class SendMessage;
@class ValidateAddressMessage;
@class FeeResponse;
@class SendTransactionResponse;
@class BlockchainErrorMessage;
@class BalanceResponse;
@class CurrencyInfoMessage;
@class CardMessage;
@class TransactionHistoryRequest;
@class TransactionsHistory;
@class CommandResponse;
@class SendCommandMessage;
@class ChainKeyMessage;
@class ChainKeyInfo;

@interface FeeMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSymbol:(NSString *)symbol
    blockchain:(NSString *)blockchain
    currencyType:(NSString *)currencyType
    receiverAddress:(NSString *)receiverAddress
    sumToSend:(NSString *)sumToSend
    isTest:(NSString *)isTest;
@property(nonatomic, copy) NSString * symbol;
@property(nonatomic, copy) NSString * blockchain;
@property(nonatomic, copy) NSString * currencyType;
@property(nonatomic, copy) NSString * receiverAddress;
@property(nonatomic, copy) NSString * sumToSend;
@property(nonatomic, copy) NSString * isTest;
@end

@interface SendMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithSymbol:(nullable NSString *)symbol
    blockchainId:(NSString *)blockchainId
    currencyType:(NSString *)currencyType
    walletAddress:(NSString *)walletAddress
    fee:(NSString *)fee
    sumToSend:(NSString *)sumToSend
    receiverAddress:(NSString *)receiverAddress
    gasLimit:(nullable NSString *)gasLimit
    gasPrice:(nullable NSString *)gasPrice
    isTest:(NSString *)isTest;
@property(nonatomic, copy, nullable) NSString * symbol;
@property(nonatomic, copy) NSString * blockchainId;
@property(nonatomic, copy) NSString * currencyType;
@property(nonatomic, copy) NSString * walletAddress;
@property(nonatomic, copy) NSString * fee;
@property(nonatomic, copy) NSString * sumToSend;
@property(nonatomic, copy) NSString * receiverAddress;
@property(nonatomic, copy, nullable) NSString * gasLimit;
@property(nonatomic, copy, nullable) NSString * gasPrice;
@property(nonatomic, copy) NSString * isTest;
@end

@interface ValidateAddressMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithBlockchain:(NSString *)blockchain
    address:(NSString *)address
    isTest:(NSString *)isTest;
@property(nonatomic, copy) NSString * blockchain;
@property(nonatomic, copy) NSString * address;
@property(nonatomic, copy) NSString * isTest;
@end

@interface FeeResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithType:(FeeType)type
    value:(NSNumber *)value
    gasLimit:(nullable NSString *)gasLimit
    gasPrice:(nullable NSString *)gasPrice;
@property(nonatomic, assign) FeeType type;
@property(nonatomic, strong) NSNumber * value;
@property(nonatomic, copy, nullable) NSString * gasLimit;
@property(nonatomic, copy, nullable) NSString * gasPrice;
@end

@interface SendTransactionResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithIsSuccess:(NSNumber *)isSuccess
    errorMsg:(nullable NSString *)errorMsg;
@property(nonatomic, strong) NSNumber * isSuccess;
@property(nonatomic, copy, nullable) NSString * errorMsg;
@end

@interface BlockchainErrorMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCode:(NSNumber *)code
    customMessage:(NSString *)customMessage;
@property(nonatomic, strong) NSNumber * code;
@property(nonatomic, copy) NSString * customMessage;
@end

@interface BalanceResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithData:(CurrencyInfoMessage *)data
    errorMessage:(nullable BlockchainErrorMessage *)errorMessage;
@property(nonatomic, strong) CurrencyInfoMessage * data;
@property(nonatomic, strong, nullable) BlockchainErrorMessage * errorMessage;
@end

@interface CurrencyInfoMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    icon:(NSString *)icon
    name:(NSString *)name
    networkId:(NSString *)networkId
    networkName:(nullable NSString *)networkName
    networkIcon:(NSString *)networkIcon
    symbol:(NSString *)symbol
    contractAddress:(nullable NSString *)contractAddress
    decimalCount:(nullable NSNumber *)decimalCount
    amount:(nullable NSNumber *)amount
    address:(nullable NSString *)address
    publicKey:(nullable FlutterStandardTypedData *)publicKey
    chainCode:(nullable FlutterStandardTypedData *)chainCode
    isTest:(nullable NSNumber *)isTest;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, copy) NSString * icon;
@property(nonatomic, copy) NSString * name;
@property(nonatomic, copy) NSString * networkId;
@property(nonatomic, copy, nullable) NSString * networkName;
@property(nonatomic, copy) NSString * networkIcon;
@property(nonatomic, copy) NSString * symbol;
@property(nonatomic, copy, nullable) NSString * contractAddress;
@property(nonatomic, strong, nullable) NSNumber * decimalCount;
@property(nonatomic, strong, nullable) NSNumber * amount;
@property(nonatomic, copy, nullable) NSString * address;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * publicKey;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * chainCode;
@property(nonatomic, strong, nullable) NSNumber * isTest;
@end

@interface CardMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithUid:(NSString *)uid
    isPasswordSet:(NSNumber *)isPasswordSet
    publicKey:(nullable FlutterStandardTypedData *)publicKey
    currencyList:(NSArray<CurrencyInfoMessage *> *)currencyList;
@property(nonatomic, copy) NSString * uid;
@property(nonatomic, strong) NSNumber * isPasswordSet;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * publicKey;
@property(nonatomic, strong) NSArray<CurrencyInfoMessage *> * currencyList;
@end

@interface TransactionHistoryRequest : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithAddress:(NSString *)address
    page:(nullable NSString *)page
    type:(NSNumber *)type
    currencyInfo:(CurrencyInfoMessage *)currencyInfo;
@property(nonatomic, copy) NSString * address;
@property(nonatomic, copy, nullable) NSString * page;
@property(nonatomic, strong) NSNumber * type;
@property(nonatomic, strong) CurrencyInfoMessage * currencyInfo;
@end

@interface TransactionsHistory : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithTime:(NSNumber *)time
    direction:(NSNumber *)direction
    status:(NSNumber *)status
    type:(NSNumber *)type
    value:(NSNumber *)value
    decimals:(NSNumber *)decimals;
@property(nonatomic, strong) NSNumber * time;
@property(nonatomic, strong) NSNumber * direction;
@property(nonatomic, strong) NSNumber * status;
@property(nonatomic, strong) NSNumber * type;
@property(nonatomic, strong) NSNumber * value;
@property(nonatomic, strong) NSNumber * decimals;
@end

/// [cardId]卡片ID
/// [data]命令结果
@interface CommandResponse : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCardId:(NSString *)cardId
    appletVersionCode:(NSString *)appletVersionCode
    isActivated:(NSNumber *)isActivated
    resetCount:(NSNumber *)resetCount
    data:(nullable FlutterStandardTypedData *)data;
@property(nonatomic, copy) NSString * cardId;
@property(nonatomic, copy) NSString * appletVersionCode;
@property(nonatomic, strong) NSNumber * isActivated;
@property(nonatomic, strong) NSNumber * resetCount;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * data;
@end

/// [command]请求命令数据
/// [checkPwd]是否需要检查密码
/// [checkLock]是否需要检查卡片已锁
/// [ndefLink]是否需要设置ndefLink
/// ///[ndefLink]是否需要设置ndefLink
@interface SendCommandMessage : NSObject
+ (instancetype)makeWithAppletId:(nullable FlutterStandardTypedData *)appletId
    cardId:(nullable NSString *)cardId
    command:(nullable FlutterStandardTypedData *)command
    checkLock:(nullable NSNumber *)checkLock
    ndefLink:(nullable NSString *)ndefLink
    cardNo:(nullable NSString *)cardNo
    checkPwd:(nullable NSNumber *)checkPwd;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * appletId;
@property(nonatomic, copy, nullable) NSString * cardId;
@property(nonatomic, strong, nullable) FlutterStandardTypedData * command;
@property(nonatomic, strong, nullable) NSNumber * checkLock;
@property(nonatomic, copy, nullable) NSString * ndefLink;
@property(nonatomic, copy, nullable) NSString * cardNo;
@property(nonatomic, strong, nullable) NSNumber * checkPwd;
@end

@interface ChainKeyMessage : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithBlockchainId:(NSString *)blockchainId
    chainId:(nullable NSNumber *)chainId
    privateKey:(NSString *)privateKey
    publicKey:(NSString *)publicKey
    address:(NSString *)address;
@property(nonatomic, copy) NSString * blockchainId;
@property(nonatomic, strong, nullable) NSNumber * chainId;
@property(nonatomic, copy) NSString * privateKey;
@property(nonatomic, copy) NSString * publicKey;
@property(nonatomic, copy) NSString * address;
@end

@interface ChainKeyInfo : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithCardId:(NSString *)cardId
    chainKeys:(NSArray<ChainKeyMessage *> *)chainKeys;
@property(nonatomic, copy) NSString * cardId;
@property(nonatomic, strong) NSArray<ChainKeyMessage *> * chainKeys;
@end

/// The codec used by BlockchainApi.
NSObject<FlutterMessageCodec> *BlockchainApiGetCodec(void);

@protocol BlockchainApi
/// 发送拍卡命令
/// [command]请求命令数据
/// [checkPwd]是否需要检查密码
/// [checkLock]是否需要检查卡片已锁
- (void)scanCardWithCommandSendCommandMessage:(SendCommandMessage *)sendCommandMessage completion:(void (^)(CommandResponse *_Nullable, FlutterError *_Nullable))completion;
- (void)scanCardAndDeriveCurrencyList:(NSArray<CurrencyInfoMessage *> *)currencyList ndefLink:(NSString *)ndefLink cardId:(nullable NSString *)cardId cardNo:(nullable NSString *)cardNo completion:(void (^)(CardMessage *_Nullable, FlutterError *_Nullable))completion;
- (void)createWalletAndDeriveCurrencyList:(NSArray<CurrencyInfoMessage *> *)currencyList completion:(void (^)(CardMessage *_Nullable, FlutterError *_Nullable))completion;
- (void)loadCurrencyInfoListCurrencyList:(NSArray<CurrencyInfoMessage *> *)currencyList completion:(void (^)(FlutterError *_Nullable))completion;
/// 初始化钱包
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)initScanResponseUuid:(NSString *)uuid error:(FlutterError *_Nullable *_Nonnull)error;
///添加币种
- (void)addCurrencyListCurrencyList:(NSArray<CurrencyInfoMessage *> *)currencyList completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
///获取交易手续费
- (void)getFeeFeeMessage:(FeeMessage *)feeMessage completion:(void (^)(NSArray<FeeResponse *> *_Nullable, FlutterError *_Nullable))completion;
///发送交易合约
- (void)sendTransactionSendMessage:(SendMessage *)sendMessage completion:(void (^)(SendTransactionResponse *_Nullable, FlutterError *_Nullable))completion;
/// 验证钱包地址
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)validateAddressValidateMessage:(ValidateAddressMessage *)validateMessage error:(FlutterError *_Nullable *_Nonnull)error;
///清除原生币种缓存数据
- (void)clearLocalCurrencyCardId:(NSString *)cardId coinIds:(NSArray<NSString *> *)coinIds error:(FlutterError *_Nullable *_Nonnull)error;
- (void)loadTransactionHistoryListRequest:(TransactionHistoryRequest *)request completion:(void (^)(NSArray<TransactionsHistory *> *_Nullable, FlutterError *_Nullable))completion;
///切换钱包
- (void)changeWalletCardId:(NSString *)cardId currencyList:(NSArray<CurrencyInfoMessage *> *)currencyList completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
///上传奔溃信息
- (void)postCatchedExceptionError:(NSString *)error completion:(void (^)(FlutterError *_Nullable))completion;
- (void)signLightningSignText:(NSString *)signText isBtc:(NSNumber *)isBtc completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)createChainKeysBlockchains:(NSArray<NSString *> *)blockchains completion:(void (^)(ChainKeyInfo *_Nullable, FlutterError *_Nullable))completion;
- (void)getChainKeysCardId:(NSString *)cardId blockchains:(NSArray<NSString *> *)blockchains completion:(void (^)(NSArray<ChainKeyMessage *> *_Nullable, FlutterError *_Nullable))completion;
- (void)signTextBlockchainId:(NSString *)blockchainId text:(FlutterStandardTypedData *)text chainId:(nullable NSNumber *)chainId completion:(void (^)(FlutterStandardTypedData *_Nullable, FlutterError *_Nullable))completion;
- (void)signTransactionBlockchainId:(NSString *)blockchainId text:(FlutterStandardTypedData *)text chainId:(nullable NSNumber *)chainId completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getBitcoinPublicKeyWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)resetNfcReaderModeWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSString *)getEthPublicKeyWithError:(FlutterError *_Nullable *_Nonnull)error;
- (void)makeAddressesNetworkId:(NSString *)networkId isBtc:(NSNumber *)isBtc completion:(void (^)(NSString *_Nullable, FlutterError *_Nullable))completion;
- (void)bindNetworkWithError:(FlutterError *_Nullable *_Nonnull)error;
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isVpnActiveWithError:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpBlockchainApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<BlockchainApi> *_Nullable api);

/// The codec used by FlutterClientApi.
NSObject<FlutterMessageCodec> *FlutterClientApiGetCodec(void);

@interface FlutterClientApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
///更新数字币余额信息
- (void)updateCurrencyInfoCurrencyInfoList:(NSArray<BalanceResponse *> *)currencyInfoList completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

NS_ASSUME_NONNULL_END
