class PageFieldConfigInfo {
  bool? isShowKLine = false;
  bool? isShowLineChart = false;
  bool? isShowCardTotalBalance = false;
  bool? isShowTotalInvestment = false;
  bool? isShowCurValue = false;
  bool? isShowCurPirce = false;
  bool? isShowProfit = false;
  bool? isShowRoi = false;
  bool? isShowPreformace = false;
  bool? isShowCardNo = false;
  bool? isShowCardplan = false;
  bool? isShowCardbalance = false;
  bool? isShowCardMount = false;
  bool? isShowCardExecutedCount = false;
  bool? isShowCardCycle = false;
  bool? isShowCardAddCollection = false;
  bool? isShowCardMaxPeriods = false;
  bool? isShowPostCardName = false;
  bool? isShowPostCardMobile = false;
  bool? isShowPostCardIcon = true;
  bool? isShowPostCardEmail = false;
  bool? isShowPostCardAddress = false;
  bool? isShowPostCardPlan = false;
  bool? isShowPostCardCycle = false;
  bool? isShowPostCardReTap = false;
  bool? isShowPostCardActivation = false;
  bool? isShowPostCardContact = false;
  bool? isShowPStatus = false;
  bool? isShowDapplist = false;
  bool? isShowCardDetail = false;
  bool? isShowCardDescription = false;
  bool? isShowCardIcon = true;
  bool? isShowWallet = false;
  bool? isShowCardLogo = false;
  bool? isShowCardBrand = false;
  bool? isShowCardBrandImage = false;
  bool? isShowCardShape = false;
  bool? isShowCardShapeImage = false;
  bool? isShowCardMerchantLogo = false;
  bool? isShowCardMerchantName = false;
  bool? isShowCardMerchantTitle = false;
  bool? isShowCardBackgroundImage = false;
  bool? isShowCardChainStamp = false;

  PageFieldConfigInfo({
    this.isShowKLine = false,
    this.isShowLineChart = false,
    this.isShowCardTotalBalance = false,
    this.isShowTotalInvestment = false,
    this.isShowCurValue = false,
    this.isShowCurPirce = false,
    this.isShowProfit = false,
    this.isShowRoi = false,
    this.isShowPreformace = false,
    this.isShowCardNo = false,
    this.isShowCardplan = false,
    this.isShowCardbalance = false,
    this.isShowCardMount = false,
    this.isShowCardExecutedCount = false,
    this.isShowCardCycle = false,
    this.isShowCardAddCollection = false,
    this.isShowCardMaxPeriods = false,
    this.isShowPostCardName = false,
    this.isShowPostCardMobile = false,
    this.isShowPostCardIcon = true,
    this.isShowPostCardEmail = false,
    this.isShowPostCardAddress = false,
    this.isShowPostCardPlan = false,
    this.isShowPostCardCycle = false,
    this.isShowPostCardReTap = false,
    this.isShowPostCardActivation = false,
    this.isShowPostCardContact = false,
    this.isShowPStatus = false,
    this.isShowDapplist = false,
    this.isShowCardDetail = false,
    this.isShowCardDescription = false,
    this.isShowCardIcon = true,
    this.isShowWallet = false,
    this.isShowCardLogo = false,
    this.isShowCardBrand = false,
    this.isShowCardBrandImage = false,
    this.isShowCardShape = false,
    this.isShowCardShapeImage = false,
    this.isShowCardMerchantLogo = false,
    this.isShowCardMerchantName = false,
    this.isShowCardMerchantTitle = false,
    this.isShowCardBackgroundImage = false,
    this.isShowCardChainStamp = false,
  });
}
