// Autogenerated from Pigeon (v12.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

enum FeeType {
  low,
  normal,
  priority,
}

enum CurrencyType {
  coin,
  token,
}

class FeeMessage {
  FeeMessage({
    required this.symbol,
    required this.blockchain,
    required this.currencyType,
    required this.receiverAddress,
    required this.sumToSend,
    required this.isTest,
  });

  String symbol;

  String blockchain;

  String currencyType;

  String receiverAddress;

  String sumToSend;

  String isTest;

  Object encode() {
    return <Object?>[
      symbol,
      blockchain,
      currencyType,
      receiverAddress,
      sumToSend,
      isTest,
    ];
  }

  static FeeMessage decode(Object result) {
    result as List<Object?>;
    return FeeMessage(
      symbol: result[0]! as String,
      blockchain: result[1]! as String,
      currencyType: result[2]! as String,
      receiverAddress: result[3]! as String,
      sumToSend: result[4]! as String,
      isTest: result[5]! as String,
    );
  }
}

class SendMessage {
  SendMessage({
    this.symbol,
    required this.blockchainId,
    required this.currencyType,
    required this.walletAddress,
    required this.fee,
    required this.sumToSend,
    required this.receiverAddress,
    this.gasLimit,
    this.gasPrice,
    required this.isTest,
  });

  String? symbol;

  String blockchainId;

  String currencyType;

  String walletAddress;

  String fee;

  String sumToSend;

  String receiverAddress;

  String? gasLimit;

  String? gasPrice;

  String isTest;

  Object encode() {
    return <Object?>[
      symbol,
      blockchainId,
      currencyType,
      walletAddress,
      fee,
      sumToSend,
      receiverAddress,
      gasLimit,
      gasPrice,
      isTest,
    ];
  }

  static SendMessage decode(Object result) {
    result as List<Object?>;
    return SendMessage(
      symbol: result[0] as String?,
      blockchainId: result[1]! as String,
      currencyType: result[2]! as String,
      walletAddress: result[3]! as String,
      fee: result[4]! as String,
      sumToSend: result[5]! as String,
      receiverAddress: result[6]! as String,
      gasLimit: result[7] as String?,
      gasPrice: result[8] as String?,
      isTest: result[9]! as String,
    );
  }
}

class ValidateAddressMessage {
  ValidateAddressMessage({
    required this.blockchain,
    required this.address,
    required this.isTest,
  });

  String blockchain;

  String address;

  String isTest;

  Object encode() {
    return <Object?>[
      blockchain,
      address,
      isTest,
    ];
  }

  static ValidateAddressMessage decode(Object result) {
    result as List<Object?>;
    return ValidateAddressMessage(
      blockchain: result[0]! as String,
      address: result[1]! as String,
      isTest: result[2]! as String,
    );
  }
}

class FeeResponse {
  FeeResponse({
    required this.type,
    required this.value,
    this.gasLimit,
    this.gasPrice,
  });

  FeeType type;

  String value;

  String? gasLimit;

  String? gasPrice;

  Object encode() {
    return <Object?>[
      type.index,
      value,
      gasLimit,
      gasPrice,
    ];
  }

  static FeeResponse decode(Object result) {
    result as List<Object?>;
    return FeeResponse(
      type: FeeType.values[result[0]! as int],
      value: result[1]! as String,
      gasLimit: result[2] as String?,
      gasPrice: result[3] as String?,
    );
  }
}

class SendTransactionResponse {
  SendTransactionResponse({
    required this.isSuccess,
    this.errorMsg,
  });

  bool isSuccess;

  String? errorMsg;

  Object encode() {
    return <Object?>[
      isSuccess,
      errorMsg,
    ];
  }

  static SendTransactionResponse decode(Object result) {
    result as List<Object?>;
    return SendTransactionResponse(
      isSuccess: result[0]! as bool,
      errorMsg: result[1] as String?,
    );
  }
}

class BlockchainErrorMessage {
  BlockchainErrorMessage({
    required this.code,
    required this.customMessage,
  });

  int code;

  String customMessage;

  Object encode() {
    return <Object?>[
      code,
      customMessage,
    ];
  }

  static BlockchainErrorMessage decode(Object result) {
    result as List<Object?>;
    return BlockchainErrorMessage(
      code: result[0]! as int,
      customMessage: result[1]! as String,
    );
  }
}

class BalanceResponse {
  BalanceResponse({
    required this.data,
    this.errorMessage,
  });

  CurrencyInfoMessage data;

  BlockchainErrorMessage? errorMessage;

  Object encode() {
    return <Object?>[
      data.encode(),
      errorMessage?.encode(),
    ];
  }

  static BalanceResponse decode(Object result) {
    result as List<Object?>;
    return BalanceResponse(
      data: CurrencyInfoMessage.decode(result[0]! as List<Object?>),
      errorMessage: result[1] != null
          ? BlockchainErrorMessage.decode(result[1]! as List<Object?>)
          : null,
    );
  }
}

class CurrencyInfoMessage {
  CurrencyInfoMessage({
    required this.id,
    required this.icon,
    required this.name,
    required this.networkId,
    this.networkName,
    required this.networkIcon,
    required this.symbol,
    this.contractAddress,
    this.decimalCount,
    this.amount,
    this.address,
    this.publicKey,
    this.chainCode,
    this.isTest,
  });

  String id;

  String icon;

  String name;

  String networkId;

  String? networkName;

  String networkIcon;

  String symbol;

  String? contractAddress;

  int? decimalCount;

  String? amount;

  String? address;

  Uint8List? publicKey;

  Uint8List? chainCode;

  int? isTest;

  Object encode() {
    return <Object?>[
      id,
      icon,
      name,
      networkId,
      networkName,
      networkIcon,
      symbol,
      contractAddress,
      decimalCount,
      amount,
      address,
      publicKey,
      chainCode,
      isTest,
    ];
  }

  static CurrencyInfoMessage decode(Object result) {
    result as List<Object?>;
    return CurrencyInfoMessage(
      id: result[0]! as String,
      icon: result[1]! as String,
      name: result[2]! as String,
      networkId: result[3]! as String,
      networkName: result[4] as String?,
      networkIcon: result[5]! as String,
      symbol: result[6]! as String,
      contractAddress: result[7] as String?,
      decimalCount: result[8] as int?,
      amount: result[9] as String?,
      address: result[10] as String?,
      publicKey: result[11] as Uint8List?,
      chainCode: result[12] as Uint8List?,
      isTest: result[13] as int?,
    );
  }
}

class CardMessage {
  CardMessage({
    required this.uid,
    required this.isPasswordSet,
    this.publicKey,
    required this.currencyList,
  });

  String uid;

  bool isPasswordSet;

  Uint8List? publicKey;

  List<CurrencyInfoMessage?> currencyList;

  Object encode() {
    return <Object?>[
      uid,
      isPasswordSet,
      publicKey,
      currencyList,
    ];
  }

  static CardMessage decode(Object result) {
    result as List<Object?>;
    return CardMessage(
      uid: result[0]! as String,
      isPasswordSet: result[1]! as bool,
      publicKey: result[2] as Uint8List?,
      currencyList: (result[3] as List<Object?>?)!.cast<CurrencyInfoMessage?>(),
    );
  }
}

class TransactionHistoryRequest {
  TransactionHistoryRequest({
    required this.address,
    this.page,
    required this.type,
    required this.currencyInfo,
  });

  String address;

  String? page;

  int type;

  CurrencyInfoMessage currencyInfo;

  Object encode() {
    return <Object?>[
      address,
      page,
      type,
      currencyInfo.encode(),
    ];
  }

  static TransactionHistoryRequest decode(Object result) {
    result as List<Object?>;
    return TransactionHistoryRequest(
      address: result[0]! as String,
      page: result[1] as String?,
      type: result[2]! as int,
      currencyInfo: CurrencyInfoMessage.decode(result[3]! as List<Object?>),
    );
  }
}

class TransactionsHistory {
  TransactionsHistory({
    required this.time,
    required this.direction,
    required this.status,
    required this.type,
    required this.value,
    required this.decimals,
  });

  int time;

  int direction;

  int status;

  int type;

  double value;

  int decimals;

  Object encode() {
    return <Object?>[
      time,
      direction,
      status,
      type,
      value,
      decimals,
    ];
  }

  static TransactionsHistory decode(Object result) {
    result as List<Object?>;
    return TransactionsHistory(
      time: result[0]! as int,
      direction: result[1]! as int,
      status: result[2]! as int,
      type: result[3]! as int,
      value: result[4]! as double,
      decimals: result[5]! as int,
    );
  }
}

/// [cardId]卡片ID
/// [data]命令结果
class CommandResponse {
  CommandResponse({
    required this.cardId,
    required this.appletVersionCode,
    required this.appletVersion,
    required this.isActivated,
    required this.resetCount,
    this.data,
  });

  String cardId;

  String appletVersionCode;

  String appletVersion;

  bool isActivated;

  int resetCount;

  Uint8List? data;

  Object encode() {
    return <Object?>[
      cardId,
      appletVersionCode,
      appletVersion,
      isActivated,
      resetCount,
      data,
    ];
  }

  static CommandResponse decode(Object result) {
    result as List<Object?>;
    return CommandResponse(
      cardId: result[0]! as String,
      appletVersionCode: result[1]! as String,
      appletVersion: result[2]! as String,
      isActivated: result[3]! as bool,
      resetCount: result[4]! as int,
      data: result[5] as Uint8List?,
    );
  }
}

/// [command]请求命令数据
/// [checkPwd]是否需要检查密码
/// [checkLock]是否需要检查卡片已锁
/// [ndefLink]是否需要设置ndefLink
/// ///[ndefLink]是否需要设置ndefLink
class SendCommandMessage {
  SendCommandMessage({
    this.appletId,
    this.cardId,
    this.command,
    this.checkLock,
    this.ndefLink,
    this.ndefAar,
    this.cardNo,
    this.checkPwd,
    this.needRun,
    this.needSyscUid,
  });

  Uint8List? appletId;

  String? cardId;

  Uint8List? command;

  bool? checkLock;

  String? ndefLink;

  String? ndefAar;

  String? cardNo;

  bool? checkPwd;

  bool? needRun;

  bool? needSyscUid;

  Object encode() {
    return <Object?>[
      appletId,
      cardId,
      command,
      checkLock,
      ndefLink,
      ndefAar,
      cardNo,
      checkPwd,
      needRun,
      needSyscUid,
    ];
  }

  static SendCommandMessage decode(Object result) {
    result as List<Object?>;
    return SendCommandMessage(
      appletId: result[0] as Uint8List?,
      cardId: result[1] as String?,
      command: result[2] as Uint8List?,
      checkLock: result[3] as bool?,
      ndefLink: result[4] as String?,
      ndefAar: result[5] as String?,
      cardNo: result[6] as String?,
      checkPwd: result[7] as bool?,
      needRun: result[8] as bool?,
      needSyscUid: result[9] as bool?,
    );
  }
}

class ChainKeyMessage {
  ChainKeyMessage({
    required this.blockchainId,
    this.chainId,
    required this.privateKey,
    required this.publicKey,
    required this.address,
  });

  String blockchainId;

  int? chainId;

  String privateKey;

  String publicKey;

  String address;

  Object encode() {
    return <Object?>[
      blockchainId,
      chainId,
      privateKey,
      publicKey,
      address,
    ];
  }

  static ChainKeyMessage decode(Object result) {
    result as List<Object?>;
    return ChainKeyMessage(
      blockchainId: result[0]! as String,
      chainId: result[1] as int?,
      privateKey: result[2]! as String,
      publicKey: result[3]! as String,
      address: result[4]! as String,
    );
  }
}

class ChainKeyInfo {
  ChainKeyInfo({
    required this.cardId,
    required this.chainKeys,
  });

  String cardId;

  List<ChainKeyMessage?> chainKeys;

  Object encode() {
    return <Object?>[
      cardId,
      chainKeys,
    ];
  }

  static ChainKeyInfo decode(Object result) {
    result as List<Object?>;
    return ChainKeyInfo(
      cardId: result[0]! as String,
      chainKeys: (result[1] as List<Object?>?)!.cast<ChainKeyMessage?>(),
    );
  }
}

class _BlockchainApiCodec extends StandardMessageCodec {
  const _BlockchainApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is CardMessage) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is ChainKeyInfo) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is ChainKeyMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is CommandResponse) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is CurrencyInfoMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is FeeMessage) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is FeeResponse) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is SendCommandMessage) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is SendMessage) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is SendTransactionResponse) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is TransactionHistoryRequest) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is TransactionsHistory) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is ValidateAddressMessage) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return CardMessage.decode(readValue(buffer)!);
      case 129: 
        return ChainKeyInfo.decode(readValue(buffer)!);
      case 130: 
        return ChainKeyMessage.decode(readValue(buffer)!);
      case 131: 
        return CommandResponse.decode(readValue(buffer)!);
      case 132: 
        return CurrencyInfoMessage.decode(readValue(buffer)!);
      case 133: 
        return FeeMessage.decode(readValue(buffer)!);
      case 134: 
        return FeeResponse.decode(readValue(buffer)!);
      case 135: 
        return SendCommandMessage.decode(readValue(buffer)!);
      case 136: 
        return SendMessage.decode(readValue(buffer)!);
      case 137: 
        return SendTransactionResponse.decode(readValue(buffer)!);
      case 138: 
        return TransactionHistoryRequest.decode(readValue(buffer)!);
      case 139: 
        return TransactionsHistory.decode(readValue(buffer)!);
      case 140: 
        return ValidateAddressMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class BlockchainApi {
  /// Constructor for [BlockchainApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  BlockchainApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _BlockchainApiCodec();

  /// 发送拍卡命令
  /// [command]请求命令数据
  /// [checkPwd]是否需要检查密码
  /// [checkLock]是否需要检查卡片已锁
  Future<CommandResponse> scanCardWithCommand(SendCommandMessage arg_sendCommandMessage) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.scanCardWithCommand', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_sendCommandMessage]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as CommandResponse?)!;
    }
  }

  Future<CardMessage> scanCardAndDerive(List<CurrencyInfoMessage?> arg_currencyList, String arg_ndefLink, String? arg_cardId, String? arg_cardNo) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.scanCardAndDerive', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_currencyList, arg_ndefLink, arg_cardId, arg_cardNo]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as CardMessage?)!;
    }
  }

  Future<CardMessage> createWalletAndDerive(List<CurrencyInfoMessage?> arg_currencyList) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.createWalletAndDerive', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_currencyList]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as CardMessage?)!;
    }
  }

  Future<void> loadCurrencyInfoList(List<CurrencyInfoMessage?> arg_currencyList) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.loadCurrencyInfoList', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_currencyList]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  ///初始化钱包
  Future<bool> initScanResponse(String arg_uuid) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.initScanResponse', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_uuid]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }

  ///添加币种
  Future<bool> addCurrencyList(List<CurrencyInfoMessage?> arg_currencyList) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.addCurrencyList', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_currencyList]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }

  ///获取交易手续费
  Future<List<FeeResponse?>> getFee(FeeMessage arg_feeMessage) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.getFee', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_feeMessage]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as List<Object?>?)!.cast<FeeResponse?>();
    }
  }

  ///发送交易合约
  Future<SendTransactionResponse> sendTransaction(SendMessage arg_sendMessage) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.sendTransaction', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_sendMessage]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as SendTransactionResponse?)!;
    }
  }

  ///验证钱包地址
  Future<bool> validateAddress(ValidateAddressMessage arg_validateMessage) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.validateAddress', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_validateMessage]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }

  ///清除原生币种缓存数据
  Future<void> clearLocalCurrency(String arg_cardId, List<String?> arg_coinIds) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.clearLocalCurrency', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_cardId, arg_coinIds]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<List<TransactionsHistory?>> loadTransactionHistoryList(TransactionHistoryRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.loadTransactionHistoryList', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as List<Object?>?)!.cast<TransactionsHistory?>();
    }
  }

  ///切换钱包
  Future<bool> changeWallet(String arg_cardId, List<CurrencyInfoMessage?> arg_currencyList) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.changeWallet', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_cardId, arg_currencyList]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }

  ///上传奔溃信息
  Future<void> postCatchedException(String arg_error) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.postCatchedException', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_error]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> signLightning(String arg_signText, bool arg_isBtc) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.signLightning', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_signText, arg_isBtc]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<ChainKeyInfo> createChainKeys(List<String?> arg_blockchains) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.createChainKeys', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_blockchains]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as ChainKeyInfo?)!;
    }
  }

  Future<List<ChainKeyMessage?>> getChainKeys(String arg_cardId, List<String?> arg_blockchains) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.getChainKeys', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_cardId, arg_blockchains]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as List<Object?>?)!.cast<ChainKeyMessage?>();
    }
  }

  Future<String> signText(String arg_blockchainId, String arg_text, int? arg_chainId) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.signText', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_blockchainId, arg_text, arg_chainId]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<String> signTransaction(String arg_blockchainId, String arg_text, int? arg_chainId) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.signTransaction', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_blockchainId, arg_text, arg_chainId]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<String> generateKey() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.generateKey', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<String> signChallenge(String arg_challenge) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.signChallenge', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_challenge]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<String> getBitcoinPublicKey() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.getBitcoinPublicKey', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<void> resetNfcReaderMode() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.resetNfcReaderMode', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> getEthPublicKey() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.getEthPublicKey', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<String> makeAddresses(String arg_networkId, bool arg_isBtc) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.makeAddresses', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_networkId, arg_isBtc]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<void> bindNetwork() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.bindNetwork', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<bool> isVpnActive() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.isVpnActive', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }

  Future<bool> isDualSim() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.card_coin.BlockchainApi.isDualSim', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as bool?)!;
    }
  }
}

class _FlutterClientApiCodec extends StandardMessageCodec {
  const _FlutterClientApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is BalanceResponse) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is BlockchainErrorMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is CurrencyInfoMessage) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return BalanceResponse.decode(readValue(buffer)!);
      case 129: 
        return BlockchainErrorMessage.decode(readValue(buffer)!);
      case 130: 
        return CurrencyInfoMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class FlutterClientApi {
  static const MessageCodec<Object?> codec = _FlutterClientApiCodec();

  ///更新数字币余额信息
  bool updateCurrencyInfo(List<BalanceResponse?> currencyInfoList);

  static void setup(FlutterClientApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.card_coin.FlutterClientApi.updateCurrencyInfo', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.card_coin.FlutterClientApi.updateCurrencyInfo was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final List<BalanceResponse?>? arg_currencyInfoList = (args[0] as List<Object?>?)?.cast<BalanceResponse?>();
          assert(arg_currencyInfoList != null,
              'Argument for dev.flutter.pigeon.card_coin.FlutterClientApi.updateCurrencyInfo was null, expected non-null List<BalanceResponse?>.');
          try {
            final bool output = api.updateCurrencyInfo(arg_currencyInfoList!);
            return wrapResponse(result: output);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
